package io.github.kxng0109.backend.model.dto;

import lombok.Builder;

/**
 * Represents a response generated by a language model (LLM) for a given request.
 *
 * This record is used to encapsulate the output from a language model along with
 * related metadata and the identity of the specific model that generated the
 * response. It provides a structured way to deliver and organize results from
 * multiple LLMs and is typically used in applications where comparison or aggregation
 * of responses from various models is required.
 *
 * The ModelResponse includes:
 * - The identifier of the language model (llm) that generated the response.
 * - The textual response generated by the language model.
 * - The associated metadata containing detailed information about the model's
 *   behavior, performance metrics, and resource usage during this operation.
 *
 * This record is immutable and leverages the builder pattern for construction, enabling
 * easy creation of instances with specific values.
 *
 * Fields:
 * - `llm`: A string identifier that specifies which language model was used to generate the response.
 * - `response`: The generated textual response from the language model.
 * - `metadata`: An instance of {@link ModelMetadata} containing additional details such as token usage,
 *   execution time, and model-specific information.
 */
@Builder
public record ModelResponse(
        String llm,
        String response,
        ModelMetadata metadata
) {
}
