package io.github.kxng0109.backend.model.dto;

import lombok.Builder;

/**
 * Represents metadata about the operations and performance of a language model (LLM).
 *
 * This record encapsulates detailed information about a specific interaction
 * with a language model, providing insights into various metrics and attributes
 * related to its execution. It is primarily intended for monitoring, profiling,
 * and analysis of language model behavior in response to specific tasks.
 *
 * The metadata includes:
 * - `promptTokens`: The number of tokens in the input (prompt) provided to the model.
 * - `generationTokens`: The number of tokens generated by the model as output.
 * - `totalTokens`: The total number of tokens consumed during this operation, combining
 *   prompt and generation tokens.
 * - `responseTime`: The time, in milliseconds, taken by the model to generate the response.
 * - `model`: The name or identifier of the language model used for the operation.
 * - `finishReason`: The reason indicating how the generation process completed, such as
 *   reaching a token limit or a stop condition.
 * - `timestamp`: The timestamp specifying when this interaction with the model occurred.
 * - `rateLimit`: An instance of {@link ModelRateLimit} providing details about rate-limiting
 *   constraints and usage during the operation.
 *
 * This record is immutable and supports the builder pattern for straightforward and flexible
 * instantiation. It serves as a structured representation of operational insights into the
 * language model's performance and resource usage, enabling better observability and optimization.
 */
@Builder
public record ModelMetadata(
        int promptTokens,
        int generationTokens,
        int totalTokens,
        Long responseTime,
        String model,
        String finishReason,
        String timestamp,
        ModelRateLimit rateLimit
) {
}
